	package com.example.cardsagainsthumanity;
	
	public class MainMenuActivity {
	
		/**
		 * @param args
		 */
		public static void main(String[] args) {
			// TODO Autogenerated method stub
	
		}
	
	}
